---

- name: Ensure 'Windows Welcome Experience' items are disabled
  ansible.windows.win_regedit:
    hive: "C:\\Users\\{{ loop_user }}\\NTUSER.dat"
    path: HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: "{{ loop_item }}"
    data: 0
    type: dword
  loop:
    - SubscribedContent-310093Enabled
    - SubscribedContent-338388Enabled
    - SubscribedContent-338389Enabled
    - SubscribedContent-88000326Enabled
  loop_control:
    loop_var: loop_item
